repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements

- repo: https://github.com/pycqa/pylint
  rev: v2.17.4
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^custom_components/pv_forecast/.*\.py$

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3
