name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Run pylint
        run: |
          PYTHONPATH=.:$PYTHONPATH pylint $(git ls-files '*.py')

  test:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install requirements
        run: |
          pip install -r requirements_dev.txt
      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          pytest tests/test_sensor_compat.py -v
