name: Python, HACS & Home Assistant Integration CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Run pylint
        run: |
          PYTHONPATH=.:$PYTHONPATH pylint $(git ls-files '*.py')

  test:
    name: Home Assistant Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install requirements
        run: |
          pip install -r requirements_dev.txt
      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          pytest tests/test_sensor_compat.py -v

  hacs_validate:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
      - name: hassfest
        uses: home-assistant/actions/hassfest@master